import { Product } from './types';

export const PRODUCTS: Product[] = [
  {
    id: 'cap-01',
    name: 'Classic Black Snapback',
    description: 'Nuestra gorra más vendida. Diseño estructurado con cierre ajustable y logotipo bordado en alta densidad.',
    price: 85000,
    image: 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?auto=format&fit=crop&q=80&w=800',
    category: 'Headwear',
    features: ['Cierre Snapback', '100% Algodón', 'Banda antisudor'],
    inStock: true,
  },
  {
    id: 'cap-02',
    name: 'Urban Grey Dad Hat',
    description: 'Estilo relajado y minimalista. Perfecta para el uso diario con un ajuste cómodo y visera curva.',
    price: 75000,
    image: 'https://images.unsplash.com/photo-1576850738804-209827986161?auto=format&fit=crop&q=80&w=800',
    category: 'Headwear',
    features: ['Visera curva', 'Construcción desestructurada', 'Ajuste metálico'],
    inStock: true,
  },
  {
    id: 'cap-03',
    name: 'Pro Mesh Trucker',
    description: 'Malla transpirable de alta calidad para máxima frescura. Ideal para el clima cálido de Colombia.',
    price: 80000,
    image: 'https://images.unsplash.com/photo-1596455607563-ad6193f76b17?auto=format&fit=crop&q=80&w=800',
    category: 'Headwear',
    features: ['Malla Pro-Tech', 'Frontal de espuma', 'Transpirable'],
    inStock: true,
  },
  {
    id: 'cap-04',
    name: 'Signature Leather Strap',
    description: 'Edición limitada con correa de cuero genuino y acabados premium. Elevando el estilo urbano.',
    price: 120000,
    image: 'https://images.unsplash.com/photo-1521369909029-2afed882baee?auto=format&fit=crop&q=80&w=800',
    category: 'Headwear',
    features: ['Correa de cuero', 'Logo metálico', 'Caja de colección'],
    inStock: true,
  },
  {
    id: 'cap-05',
    name: 'Wild Olive Beanie',
    description: 'Para los días más fríos o para un look nocturno. Tejido suave y elástico que mantiene su forma.',
    price: 55000,
    image: 'https://images.unsplash.com/photo-1576850738692-564539656450?auto=format&fit=crop&q=80&w=800',
    category: 'Headwear',
    features: ['Tejido premium', 'Logotipo tejido', 'Talla única'],
    inStock: true,
  },
  {
    id: 'cap-06',
    name: 'Arctic White Performance',
    description: 'Gorra deportiva repelente al agua y ultra ligera. Diseñada para mantenerte seco y cómodo.',
    price: 95000,
    image: 'https://images.unsplash.com/photo-1534215754734-18e55d13e346?auto=format&fit=crop&q=80&w=800',
    category: 'Headwear',
    features: ['Repelente al agua', 'Secado rápido', 'Protección UV'],
    inStock: true,
  },
];
